name: Deploy to Elastic Beanstalk
on:
  push:
    branches:
      - main
  create:
    branches:
      - release/*
  workflow_dispatch:
    
jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: install EBS CLI
        run: |
          pip install awsebcli
          eb init -p node.js ${{secrets.EB_APP_NAME}} --region ${{secrets.AWS_REGION}}
          eb deploy ${{secrets.EB_DEV}}
          
  deploy-stg:
    if: ${{github.event.ref_type == 'branch' && startsWith(github.ref, 'refs/heads/release/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: install EBS CLI
        run: |
          pip install awsebcli
          eb init -p node.js ${{secrets.EB_APP_NAME}} --region ${{secrets.AWS_REGION}}
          eb deploy ${{secrets.EB_STAGING}}
          
  approve-prod:
    needs: deploy-stg
    if: success()
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: "Deploying to production"
        run: echo "Deploying....."
      
        
  deploy-prod:
    needs: approve-prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: install EBS CLI
        run: |
          pip install awsebcli
          eb init -p node.js ${{secrets.EB_APP_NAME}} --region ${{secrets.AWS_REGION}}
          eb deploy ${{secrets.EB_PROD}}